// Generated by CoffeeScript 1.10.0
(function() {
  var total;

  total = 20;

  co(function*() {
    var i, j, perc1, perc2, percent, prog1, prog2, ref, results;
    perc1 = $('.html5 .percent');
    prog1 = $('progress');
    perc2 = $('.bs .percent');
    prog2 = $('.progress-bar');
    results = [];
    for (i = j = 1, ref = total; 1 <= ref ? j <= ref : j >= ref; i = 1 <= ref ? ++j : --j) {
      percent = i / total * 100;
      perc1.text((percent.toFixed(0)) + "%");
      prog1.val(percent);
      perc2.text((percent.toFixed(0)) + "%");
      prog2.css('width', percent + "%");
      results.push((yield sleep(1)));
    }
    return results;
  });

}).call(this);
