// Generated by CoffeeScript 1.10.0
(function() {
  var library, sfx;

  library = {
    "select": {
      "Volume": {
        "Sustain": 0.1,
        "Decay": 0.15,
        "Punch": 0.55
      }
    },
    "long": {
      "Volume": {
        "Sustain": 0.1,
        "Decay": 0.5,
        "Punch": 1
      }
    },
    "laser": {
      "Frequency": {
        "Start": 943.3730892184989,
        "Min": 0.014185877744481512,
        "Slide": -0.7858459546681954
      },
      "Generator": {
        "Func": "string",
        "A": 0.49925120467721923,
        "ASlide": 0.051883376252668416
      },
      "Volume": {
        "Sustain": 0.18790494385019166,
        "Decay": 0.26641428396664724,
        "Punch": 0.24881662233358606
      }
    },
    'coin': jsfx.Preset.Coin
  };

  sfx = jsfx.Sounds(library);

  example('Quickstart', function(console) {
    return co(function*() {
      var key, results, value;
      (yield sleep(1));
      results = [];
      for (key in library) {
        value = library[key];
        console.log(key);
        sfx[key]();
        results.push((yield sleep(1)));
      }
      return results;
    });
  });

}).call(this);
