// Generated by CoffeeScript 1.10.0
(function() {
  var fakeConsole;

  fakeConsole = {
    log: function(obj) {
      return $('<p>').text(obj).appendTo('.console');
    }
  };

  window.example = function(title, fn) {
    $('.example-title').text(title);
    return fn(fakeConsole);
  };

  $('.nav').on('click', 'li', function(evt) {
    evt.preventDefault();
    $('.console').empty();
    $('.script-container').empty();
    return $('<script>').attr('src', evt.target.href).appendTo('.script-container');
  });

  window.sleep = function(delay) {
    return new Promise(function(resolve, reject) {
      return window.setTimeout(resolve, delay * 1000);
    });
  };

}).call(this);
