// Generated by CoffeeScript 1.10.0
(function() {
  var todo;

  todo = ['fix car', 'buy food', 'take meds', 'walk dog', 'order out', 'pick up dry cleaning'];

  example('generateWithRelativeTime', function() {
    return Rx.Observable.generateWithRelativeTime(0, function(i) {
      return i < todo.length;
    }, function(i) {
      return i + 1;
    }, function(i) {
      return todo[i];
    }, function(i) {
      return 500;
    }).subscribe(function(x) {
      return plog(x);
    });
  });

}).call(this);
