// Generated by CoffeeScript 1.10.0
(function() {
  example('range', function(console) {
    return Rx.Observable.range(103, 6).subscribe(function(x) {
      return console.log(x);
    });
  });

}).call(this);
