// Generated by CoffeeScript 1.10.0
(function() {
  var tbody, update;

  tbody = d3.select('tbody');

  $(document).ready(function() {
    return d3.csv('data0.csv', function(data) {
      return update(data);
    });
  });

  $('button.add').on('click', function() {
    return d3.csv('data1.csv', function(data) {
      return update(data);
    });
  });

  update = function(data) {
    var rows, tr;
    console.log(data);
    rows = tbody.selectAll('tr').data(data);
    tr = rows.enter().append('tr');
    rows.exit().remove();
    return tr.selectAll('td').data(function(d) {
      console.log(d3.values(d));
      return d3.values(d);
    }).enter().append('td').text(function(d) {
      return d;
    });
  };

}).call(this);
